Add credential query logic
w3c-ccg/vp-request-spec pull request #27
Opened 2023-07-28 22:33 UTC by brianorwhatever

Closes #24

2023-07-29 18:43 UTC, dlongley requested changes
Thanks! I think this can go in once we replace the "we style" language.

2023-07-29 18:43 UTC, dlongley commented on index.html
> +the top-level array is an independent requirement.
Here and everywhere else in this PR the "we style" language needs to be replaced. Here's a suggestion:

```suggestion
At the top-most level of the request structure, different types of queries are
expected to be processed as "AND" operations. Each query is a unique condition
that needs to be met to fulfill the request. This means, each query listed in
the top-level array is an independent requirement.
```

Also, for now, to avoid delaying this PR, I used "expected" language here instead of a normative statement (using "MUST" instead). I imagine we'll get more formal in the future in another pass to generate normative, testable statements for things like this.

2023-07-31 14:17 UTC, TallTed requested changes
In addition to @dlongley's comments...

2023-07-31 14:17 UTC, TallTed commented on index.html
> +In this example, we have two queries: `APopularQueryType` and
```suggestion
In this example, there are two queries: `APopularQueryType` and
```

2023-07-31 14:17 UTC, TallTed commented on index.html
> +`AnotherQueryType`. The "AND" operation here implies that both these conditions
```suggestion
`AnotherQueryType`. The "AND" operation here indicates that both these conditions
```

2023-07-31 14:17 UTC, TallTed commented on index.html
> +Within specific query types, we can define an "OR" operation. This operation
```suggestion
Within a specific query type, we can define an "OR" operation. This operation
```

2023-07-31 14:17 UTC, TallTed commented on index.html
> +indicates that any one of the nested conditions should be met. Even when all
assuming this is never an XOR ("exclusive or") operation
```suggestion
indicates that one or more of the nested conditions needs to be met. Even when all
```

2023-07-31 15:59 UTC, dmitrizagidulin approved these changes
:+1:  (once Dave & TallTed's suggestions are incorporated)

2023-07-31 17:28 UTC, brianorwhatever commented on index.html
> +absence will not halt the process.
```suggestion
In a specific query type, an "OR" operation can be defined. This operation 
indicates that one or more of the nested conditions needs to be met. Even when 
all credentialQuery objects are optional, they are interpreted as "OR" 
operations within their context. This enables flexible and forgiving data 
retrieval where optional conditions can refine the results when possible, but 
their absence will not halt the process.
```

2023-08-08 16:38 UTC, dlongley approved these changes

2023-08-08 17:12 UTC, TallTed requested changes
Tiny tweaks

2023-08-08 17:12 UTC, TallTed commented on index.html
> +In a specific query type, an "OR" operation can be defined. This operation
```suggestion
Within a specific query type, an "OR" operation can be defined. This operation 
```

2023-08-08 17:12 UTC, TallTed commented on index.html
> +indicates that one or more of the nested conditions needs to be met. Even when
```suggestion
indicates that one or more of the nested conditions needs to be met. When 
```

2023-08-08 18:03 UTC, TallTed approved these changes

2023-08-08 19:01 UTC, merged